### ISSUE TITLE
access to pretrained models

### ISSUE THREAD

**Issue by QasimWani** [KAIST-AILab/SMAAC#2]
hey @sunghoonhong 
when evaluating `wcci` i need access to a trained model in the model folder (`best_actor.pt`). Do you know how I can get access to it without having to train the agent myself? I don't have the resources to train it on GPU for 1.5 days as you mentioned in #1 .

Thanks

**Comment by sunghoonhong** [comment]
Hi,
We would update trained model checkpoint soon.

Bests,

**Comment by sunghoonhong** [comment]
We've updated the example model, so you can check out the README.

Bests,
