### ISSUE TITLE
A problem when trainning.

### ISSUE THREAD

**Issue by worldofgoo9** [KAIST-AILab/SMAAC#3]
Hello ! I am trying to run your code .After downloading and setting the dataset ,when I run with command "python test.py -n=wcci_run -s=0 -c=wcci" , there are something wrong in the function state_normalize of the class Agent.The traceback is as followed:

Traceback (most recent call last):
  File "test.py", line 172, in <module>
    trainer.train(
  File "D:\BUPT\SMAAC-master\train.py", line 160, in train
    prev_act = self.agent.act(obs, None, None)
  File "D:\BUPT\SMAAC-master\agent.py", line 187, in act
    self.stack_obs(obs)
  File "D:\BUPT\SMAAC-master\agent.py", line 150, in stack_obs
    obs_vect, self.topo = self.convert_obs(self.state_normalize(obs_vect))
  File "D:\BUPT\SMAAC-master\agent.py", line 102, in state_normalize
    s = (s - self.state_mean) / self.state_std
RuntimeError: The size of tensor a (1360) must match the size of tensor b (1266) at non-singleton dimension 1

I wonder what I should do for this . :)

**Comment by sunghoonhong** [comment]
Hello, worldofgoo9.

Which version of ```grid2op``` do you use?

**Comment by worldofgoo9** [comment]
> Hello, worldofgoo9.
> 
> Which version of `grid2op` do you use?

It is 1.6.0 .I am going to try 0.9.4 version but ,I wonder what's wrong with it at 1.6.0 version .

**Comment by sunghoonhong** [comment]
This code is based on 0.9.4 version, which is for L2RPN WCCI 2020 challenge.

I'm not following the latest version of ```Grid2Op``` but it seems there have been many updates, so it may be not compatible.

For example, according to change log in ```Grid2Op```, the ```observation``` has changed quite a lot.
>[BREAKING] (but transparent for everyone): the disc_lines attribute is now part of the environment, and is also containing integer (representing the "order" on which the lines are disconnected due to protections) rather than just boolean.
>[BREAKING] now the observation stores the information related to shunts by default. This means old logs computed with the runner might not work with this new version.

So it is crucial to match the version to run this code.

**Comment by worldofgoo9** [comment]
> This code is based on 0.9.4 version, which is for L2RPN WCCI 2020 challenge.
> 
> I'm not following the latest version of `Grid2Op` but it seems there have been many updates, so it may be not compatible.
> 
> For example, according to change log in `Grid2Op`, the `observation` has changed quite a lot.
> 
> > [BREAKING] (but transparent for everyone): the disc_lines attribute is now part of the environment, and is also containing integer (representing the "order" on which the lines are disconnected due to protections) rather than just boolean.
> > [BREAKING] now the observation stores the information related to shunts by default. This means old logs computed with the runner might not work with this new version.
> 
> So it is crucial to match the version to run this code.

Thanks for your answer! :)
