### ISSUE TITLE
The reward keeps constant when training

### ISSUE THREAD

**Issue by aut6620** [KAIST-AILab/SMAAC#4]
when training, the reward keeps constant, and every episode's reward is the same.so I want to know the reason why the result comes out.
![smaac_reward(1)](https://user-images.githubusercontent.com/73046261/157225615-66bf379c-ddc1-436f-bc50-3b2bea24d193.png)
![smaac_reward(2)](https://user-images.githubusercontent.com/73046261/157225663-0f49007d-86e1-4d8d-b8cd-023fe6864fd5.png)

**Comment by sunghoonhong** [comment]
Hi, aut6620.
Could you please write the command you used?

**Comment by aut6620** [comment]
The command I used is 'python test.py'. And I change the 'case' to 'l2rpn_case14_sandbox'. So the result became the that I committed last time.

**Comment by aut6620** [comment]
![wcci](https://user-images.githubusercontent.com/73046261/157358075-7a956c67-de49-406f-af9b-290562e5cb9c.png)

                 ↓
![sand](https://user-images.githubusercontent.com/73046261/157357907-d04c4b8c-d6d3-4e6f-b843-ca1956f8bfaa.png)

**Comment by sunghoonhong** [comment]
It seems weird.
We didn't experience such problem.

Could you provide package versions? (```pip list``` or ```conda list```)
And is it reproduced whenever you execute the command?

**Comment by aut6620** [comment]
[Uploading conda_list.txt…]()
when  I copy the command or write it myself, the result is the same.

**Comment by WZY10065** [comment]
I have the same problem... The output reward is the same.

**Comment by WZY10065** [comment]
It may be that the parameter settings are unreasonable, resulting in local optimal value. If you change the parameter such as nf, the reward value will change with iteration.
